<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Country;

class StatesTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $us = Country::where('slug', 'united-states')->first();

        DB::table('states')->insert([
            [
                'country_id' => $us->id,
                'name' => 'Alaska',
                'slug' => 'alaska',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Alabama',
                'slug' => 'alabama',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Arkansas',
                'slug' => 'arkansas',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Arizona',
                'slug' => 'arizona',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'California',
                'slug' => 'california',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Colorado',
                'slug' => 'colorado',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Connecticut',
                'slug' => 'connecticut',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'District of Columbia',
                'slug' => 'district-of-columbia',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Delaware',
                'slug' => 'delaware',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Florida',
                'slug' => 'florida',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Georgia',
                'slug' => 'georgia',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Hawaii',
                'slug' => 'hawaii',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Iowa',
                'slug' => 'iowa',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Idaho',
                'slug' => 'idaho',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Illinois',
                'slug' => 'illinois',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Indiana',
                'slug' => 'indiana',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Kansas',
                'slug' => 'kansas',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Kentucky',
                'slug' => 'kentucky',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Louisiana',
                'slug' => 'louisiana',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Massachusetts',
                'slug' => 'massachusetts',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Maryland',
                'slug' => 'maryland',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Maine',
                'slug' => 'maine',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Michigan',
                'slug' => 'michigan',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Minnesota',
                'slug' => 'minnesota',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Missouri',
                'slug' => 'missouri',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Mississippi',
                'slug' => 'mississippi',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Montana',
                'slug' => 'montana',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'North Carolina',
                'slug' => 'north-carolina',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'North Dakota',
                'slug' => 'north-dakota',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Nebraska',
                'slug' => 'nebraska',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'New Hampshire',
                'slug' => 'new-hampshire',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'New Jersey',
                'slug' => 'new-jersey',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'New Mexico',
                'slug' => 'new-mexico',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Nevada',
                'slug' => 'nevada',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'New York',
                'slug' => 'new-york',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Ohio',
                'slug' => 'ohio',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Oklahoma',
                'slug' => 'oklahoma',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Oregon',
                'slug' => 'oregon',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Pennsylvania',
                'slug' => 'pennsylvania',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Rhode Island',
                'slug' => 'rhode-island',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'South Carolina',
                'slug' => 'south-carolina',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'South Dakota',
                'slug' => 'south-dakota',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Tennessee',
                'slug' => 'tennessee',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Texas',
                'slug' => 'texas',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Utah',
                'slug' => 'utah',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Virginia',
                'slug' => 'virginia',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Vermont',
                'slug' => 'vermont',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Washington',
                'slug' => 'washington',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Wisconsin',
                'slug' => 'wisconsin',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'West Virginia',
                'slug' => 'west-virginia',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'country_id' => $us->id,
                'name' => 'Wyoming',
                'slug' => 'wyoming',
                'status' => false,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
        ]);
    }
}




