version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  # memcached:
  #   driver: ${VOLUMES_DRIVER}
  # redis:
  #   driver: ${VOLUMES_DRIVER}
  # elasticsearch:
  #   driver: ${VOLUMES_DRIVER}
services:

### Workspace Utilities ##################################
    workspace:
      build:
        context: ./laradock/workspace
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_WORKSPACE_SSH=true
          - INSTALL_IMAGEMAGICK=true
          - INSTALL_XDEBUG=false
          - INSTALL_PHPREDIS=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php/zzzlaravel.ini:/usr/local/etc/php/conf.d/zzzlaravel.ini
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "2222:22"
      networks:
        - frontend
        - backend

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./laradock/php-fpm
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_XDEBUG=true
          - INSTALL_IMAGEMAGICK=true
          - INSTALL_PHPREDIS=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./laradock/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ./php/zzzlaravel.ini:/usr/local/etc/php/conf.d/zzzlaravel.ini
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      depends_on:
        - workspace
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      build:
        context: ./laradock/nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ./php/zzzlaravel.ini:/usr/local/etc/php/conf.d/zzzlaravel.ini
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MySQL ################################################
    mysql:
      build:
        context: ./laradock/mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      command: 'mysqld --default-authentication-plugin=mysql_native_password'
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${DB_PORT}:3306"
      networks:
        - backend

### API Reference server #################################
    # apidoc:
    #   image: redocly/redoc:latest
    #   environment:
    #     - PAGE_TITLE=O Bonsai Core System API Reference
    #     - SPEC_URL=${APP_URL}/docs
    #   ports:
    #     - 81:80
    #   networks:
    #     - backend

### Redis ################################################
    # redis:
    #   build: ./laradock/redis
    #   volumes:
    #     - ${DATA_PATH_HOST}/redis:/data
    #   ports:
    #     - "${REDIS_PORT}:6379"
    #   networks:
    #     - backend

### Memcached ############################################
    # memcached:
    #   build: ./laradock/memcached
    #   volumes:
    #     - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
    #   ports:
    #     - "${MEMCACHED_HOST_PORT}:11211"
    #   depends_on:
    #     - php-fpm
    #   networks:
    #     - backend

### ElasticSearch ########################################
    # elasticsearch:
    #   build: ./laradock/elasticsearch
    #   volumes:
    #     - elasticsearch:/usr/share/elasticsearch/data
    #   environment:
    #     - cluster.name=laradock-cluster
    #     - node.name=laradock-node
    #     - bootstrap.memory_lock=true
    #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     - cluster.initial_master_nodes=laradock-node
    #   ulimits:
    #     memlock:
    #       soft: -1
    #       hard: -1
    #   ports:
    #     - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
    #     - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    #   depends_on:
    #     - php-fpm
    #   networks:
    #     - frontend
    #     - backend

### Kibana ##############################################
    # kibana:
    #   build: ./laradock/kibana
    #   ports:
    #     - "${KIBANA_HTTP_PORT}:5601"
    #   depends_on:
    #     - elasticsearch
    #   networks:
    #     - frontend
    #     - backend